run:
  timeout: 1m # default 1m

linters-settings:
  errcheck:
    check-type-assertions: true # default false
    check-blank: true # default false
    ignore: "fmt:.*" # default fmt:.*
    exclude: "" # default ""
  govet:
    enable-all: true
    settings:
      shadow:
        strict: false # default false # TODO: change to true
  structcheck:
    exported-fields: false # default false # TODO: change to true
  unused:
    check-exported: true # default false
  varcheck:
    exported-fields: true # default false
  dupl:
    threshold: 150 # default 150
  funlen:
    lines: 100 # default 60
    statements: 40 # default 40
  gocognit:
    min-complexity: 20 # minimal code complexity to report, 30 by default (but we recommend 10-20)
  goconst:
    min-len: 3 # default 3
    min-occurrences: 3 # default 3
  gocritic:
    settings:
      captLocal:
        paramsOnly: false # default true
      elseif:
        skipBalanced: false # default true
      underef:
        skipRecvDeref: false # default true
  gocyclo:
    min-complexity: 30 # default 30
  golint:
    min-confidence: 0.8 # default 0.8
  lll:
    line-length: 120 # default 120
  maligned:
    suggest-new: true # default false
  misspell:
    locale: us
    ignore-words: "" # default: ""
  nakedret:
    max-func-lines: 0 # default 30
  prealloc:
    simple: false # default true
    range-loops: true # default true
    for-loops: false # default false
  unparam:
    check-exported: true # default false
  wsl:
    strict-append: true # default true
    allow-assign-and-call: true # default true
    allow-multiline-assign: true # default true
    allow-case-trailing-whitespace: true # default true
    allow-cuddle-declarations: false # default false

linters:
  disable-all: true
  enable:
    ## enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    #- unused # TODO: find out why there are so many false positives
    - varcheck
    ## disabled by default
    - bodyclose
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - golint
    - gosec
    #- lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - unconvert
    - unparam
    - whitespace
    #- wsl # TODO: decide do we need this linter
    #- depguard # can be used to create a black list of dependencies

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: storage/
      linters: gosec
    - path: _test\.go
      linters:
        - lll
        - dupl
        - funlen
        - goconst
    - path: \.gen\.go
      linters:
        - errcheck
        - golint
