// Code generated by Effe. DO NOT EDIT.

//+build !effeinject

package main

import (
	"fmt"
)

func A(service AService) AFunc {
	return func() error {
		aVal3, err5 := service.Step1()
		if err5 != nil {
			return err5
		}
		err5 = func(aVal2 a) error {
			switch aVal2 {
			case "a":
				err3 := func(aVal a) error {
					err := service.Step2(aVal)
					if err != nil {
						return err
					}
					return nil
				}(aVal2)
				if err3 != nil {
					return err3
				}
				return nil
			case "":
				err4 := func() error {
					err2 := service.Step3()
					if err2 != nil {
						return err2
					}
					return nil
				}()
				if err4 != nil {
					return err4
				}
				return nil
			default:
				return fmt.Errorf("unsupported logic by aVal")
			}
		}(aVal3)
		if err5 != nil {
			return err5
		}
		return nil
	}
}
func NewAImpl() *AImpl {
	return &AImpl{step1FieldFunc: step1(), step2FieldFunc: step2(), step3FieldFunc: step3()}
}

type AService interface {
	Step1() (a, error)
	Step2(v a) error
	Step3() error
}
type AImpl struct {
	step1FieldFunc func() (a, error)
	step2FieldFunc func(v a) error
	step3FieldFunc func() error
}
type AFunc func() error

func (a *AImpl) Step1() (a, error) { return a.step1FieldFunc() }
func (a *AImpl) Step2(v a) error   { return a.step2FieldFunc(v) }
func (a *AImpl) Step3() error      { return a.step3FieldFunc() }
